### ISSUE TITLE
Balana fails to handle Linux hidden files

### ISSUE THREAD

**Issue by amemon** [wso2/balana#42]
Balana throws following exception, if the policy directory has ".directory'" hidden folder or hidden files like *.swp.

01-Sep-2016 13:06:38.581 SEVERE [http-nio-8445-exec-10] org.wso2.balana.finder.impl.FileBasedPolicyFinderModule.loadPolicy Fail to load policy : /home/user/aai-dev/xacml/xacml/policies/.direc
tory
 org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
        at org.wso2.balana.finder.impl.FileBasedPolicyFinderModule.loadPolicy(FileBasedPolicyFinderModule.java:220)
        at org.wso2.balana.finder.impl.FileBasedPolicyFinderModule.loadPolicies(FileBasedPolicyFinderModule.java:188)
        at org.wso2.balana.finder.impl.FileBasedPolicyFinderModule.init(FileBasedPolicyFinderModule.java:79)
        at org.wso2.balana.finder.PolicyFinder.init(PolicyFinder.java:149)
        at org.wso2.balana.PDP.<init>(PDP.java:97)
......

Do you know how to make balana lax about reading the policy directory - thanks!?

**Comment by mefarazath** [comment]
Fixed with https://github.com/wso2/balana/pull/56
