### ISSUE TITLE
Balana sample not working

### ISSUE THREAD

**Issue by mefarazath** [wso2/balana#49]
After building and trying to run the sample, it fails with the below error.

Nov 15, 2016 7:14:54 AM org.wso2.balana.ConfigurationStore setupConfig
INFO: Loading runtime configuration
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/xerces/util/SecurityManager
	at org.wso2.balana.utils.Utils.getSecuredDocumentBuilderFactory(Utils.java:107)
	at org.wso2.balana.ConfigurationStore.getRootNode(ConfigurationStore.java:309)
	at org.wso2.balana.ConfigurationStore.setupConfig(ConfigurationStore.java:201)
	at org.wso2.balana.ConfigurationStore.<init>(ConfigurationStore.java:163)
	at org.wso2.balana.Balana.<init>(Balana.java:116)
	at org.wso2.balana.Balana.getInstance(Balana.java:228)
	at org.wso2.balana.samples.custom.algo.Main.initBalana(Main.java:102)
	at org.wso2.balana.samples.custom.algo.Main.main(Main.java:47)
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.util.SecurityManager
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 8 more

after adding the 
```
<dependency>
  <groupId>xerces.wso2</groupId>
  <artifactId>xercesImpl</artifactId>
  <version>2.8.1.wso2v2</version>
</dependency>
```

manually to the lib folder in each sample it works!

**Comment by mefarazath** [comment]
Fix merged with https://github.com/wso2/balana/commit/bfddb67767e68389068860672dc2195764d5e050
